# Generated by Django 4.2.13 on 2026-06-29 05:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('grammar_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('completeness_score', models.FloatField(blank=True, null=True)),
                ('total_filler_count', models.PositiveIntegerField(default=0)),
                ('weak_areas', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='interviews.interview')),
            ],
            options={
                'db_table': 'results',
            },
        ),
    ]
